classdef Cell < common.sources.Cell
    
    methods
        
        function obj = Cell()
            import symphonyui.core.*;
            
            obj.addProperty('type', '', ...
                'type', PropertyType('char', 'row', containers.Map( ...
                    {'', 'unknown', 'RGC', 'amacrine', 'bipolar', 'horizontal', 'photoreceptor'}, ...
                    { ...
                        {}, ...
                        {}, ...
                        {'ON-parasol', 'OFF-parasol', 'ON-midget', 'OFF-midget', 'small bistratified','ON smooth monostratified','OFF smooth monostratified',...
                        'broad thorny','recursive bistratified','large bistratified','ON narrow thorny', 'OFF narrow thorny', 'ON recursive', 'ON large sparse',...
                        'OFF large sparse','ON giant sparse', 'OFF giant sparse', 'parvocellular giant', 'tufted', 'ON-OFF OS', 'ON DS', 'ON-OFF DS', 'ON', 'OFF', 'ON-OFF', 'M1 ipRGC', 'M2 ipRGC'}, ...
                        {'AII', 'A17', 'A1', 'granular', 'ON-starburst', 'OFF-starburst', 'thorny type 1', 'thorny type 2', 'ON-wiry', 'OFF-wiry', 'ON stellate varicose', 'OFF stellate varicose', 'ON', 'OFF', 'ON-OFF'}, ...
                        {'OFF-diffuse', 'OFF-midget', 'ON-diffuse', 'ON-midget', 'rod'}, ...
                        {}, ...
                        {'S cone', 'M cone', 'L cone', 'rod'} ...
                    })), ...
                'description', 'The confirmed type of the recorded cell', ...
                'isPreferred', true);
            
            obj.addAllowableParentType('io.sources.animal.Preparation');
        end
        
    end
    
end

